# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user1 = User.create!(name: 'Tiger Woods', photo: 'https://imgur.com/gallery/gsVUsjA')
user2 = User.create!(name: 'Dustin Johnson', photo: 'https://imgur.com/gallery/pOAxl')
user3 = User.create!(name: 'Ricky Fowler', photo: 'https://www.mensjournal.com/wp-content/uploads/mf/justin-thomas-golf.jpg?w=800')
user4 = User.create!(name: 'Jordan Spieth', photo: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_center,h_393,q_auto,w_713/v1/pgatour/editorial/2016/05/30/jordanspieth-847-tompennington-sm.jpg')
user5 = User.create!(name: 'Jason Day', photo: 'https://1k9pcm3i7h9szb97528k27hw-wpengine.netdna-ssl.com/wp-content/uploads/2018/05/bahle-farms-golf-club-traverse-city-jason-day-5-5-18-1030x580.png')
user6 = User.create!(name: 'Rory Mcilroy', photo: 'https://amp.businessinsider.com/images/5ab010cdcc5029da788b45ed-750-375.jpg')
user7 = User.create!(name: 'Tony Finau', photo: 'https://www.sltrib.com/resizer/lAIq4PiRl4X7W-xUfR06vXrLea8=/0x600/smart/filters:quality(86)/arc-anglerfish-arc2-prod-sltrib.s3.amazonaws.com/public/KMPFCCAD2NERRG2IARPBZWHPHE.jpg')

puts "#{User.count} users created!"

club1 = user1.clubs.create!(headline: 'Collectible Nike Vapor Pro Driver Used by Tiger Woods', brand: 'Nike', model: 'Vapor Pro Driver', loft: '8.5', club_length: '45.5in', club_color: 'white', condition: 'used', dexterity: 'right', shaft_name: 'Mitsubishi Diamana D+', shaft_flex: 'X', shaft_weight: '85gm', price: 50000.00, description:'This is a great club for collectors, the one I used before Nike shut down production of golf equipment', image:'http://www.golfalot.com/Portals/0/imagesblogs/nike/reviews/vapordriver/prosole.jpg')
club2 = Club.create!(user: user2, headline: "DJ's Scotty Cameron Putter", brand:'Titliest', model: 'Scotty Cameron Studio Newport', loft: '2.0', club_length: '38in', club_color: 'Platinum', condition: 'used', dexterity: 'right', shaft_name: 'Titleist', shaft_flex: 'stock', shaft_weight:'stock', price: 3000.00, description: 'I used this putter for years, own it now', image:'https://dks.scene7.com/is/image/GolfGalaxy/18SCNM2018SLCTNWPPTR?wid=1000&fmt=jpg')
club3 = Club.create!(user: user3, headline: 'My Cobra King F9', brand:'Cobra', model: 'King F9 Speedback Driver', loft: '10.5', club_length: '45.5in', club_color: 'yellow', condition: 'used', dexterity: 'right', shaft_name: 'Fuji Atmos', shaft_flex: 'X', shaft_weight:'65gm', price: 5000.00, description: 'One of my favorite drivers of all time', image:'https://www.americangolf.co.uk/on/demandware.static/-/Sites-master-catalog/default/dw1c1df456/images-square/zoom/343329-Cobra-King-F9-Driver-1.jpg')
club4 = Club.create!(user: user4, headline: 'Titleist Driver I Used to Win the British Open', brand:'Titleist', model: '915', loft: '9.5', club_length: '45.5in', club_color: 'black', condition: 'used', dexterity: 'right', shaft_name: 'Graphit Design Tour AD IZ-6X', shaft_flex: 'X', shaft_weight:'65gm', price: 40000.00, description: 'Own the club I used to win the British Open', image:'https://images-na.ssl-images-amazon.com/images/I/41tv2%2BSoYEL._SX425_.jpg')
club5 = Club.create!(user: user5, headline: 'My TaylorMade M6 Driver', brand: 'Taylormade', model: 'M6', loft: '9.5', club_length: '45.5in', club_color: 'Silver, Black, Red', condition: 'used', dexterity: 'right', shaft_name: 'Fujikura ATMOS', shaft_flex: 'X', shaft_weight:'70gm', price: 4500.00, description: 'I\'ve played this club for about 1 month, it\'s a great item for your golf club collection for sure!', image:'https://cdnm.golfavenue.com/catalog/product/cache/4/image/350x350/9df78eab33525d08d6e5fb8d27136e95/v/a/vapor-fly-pro-7612-1.jpg')
club6 = Club.create!(user: user6, headline: 'Nike Pro Vapor Fly Driver Used by Rory McIlroy', brand:'Nike', model: 'Pro Vapor Fly Diver', loft: '9.5', club_length: '45.5in', club_color: 'yellow', condition: 'used', dexterity: 'right', shaft_name: 'Mitsubishi Rayon Diamana Blue S+ Plus', shaft_flex: 'X', shaft_weight:'70gm', price: 40000.00, description: 'Own the club I used to win the Masters', image:'https://cdnm.golfavenue.com/catalog/product/cache/4/image/350x350/9df78eab33525d08d6e5fb8d27136e95/v/a/vapor-fly-pro-7612-1.jpg')
club7 = Club.create!(user: user7, headline: 'Buy My PING G410', brand:'Ping', model: 'G410 Plus Driver', loft: '8.5', club_length: '45.5in', club_color: 'black', condition: 'used', dexterity: 'right', shaft_name: 'Ping Tour 173-65', shaft_flex: 'X', shaft_weight:'73gm', price: 400.00, description: 'Like new, this is an extra driver that just sat in my garage', image:'https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P142823/1-f.jpg')
club8 = Club.create!(user: user1, headline: 'My King Cobra Driver Used to Win the 1997 Master', brand: 'King Cobra', model: 'Deep Face', loft: '9.0', club_length: '44in', club_color: 'silver', condition: 'used', dexterity: 'right', shaft_name: 'True Temper Dynamic Gold X100', shaft_flex: 'X100 Steel', shaft_weight: '85gm', price: 1000000.00, description:'This will probably be the most prized golf club in golfing history', image:'https://d10qo9w9xmdu7y.cloudfront.net/2017/11/Tiger-Woods-equipment-Cobra-driver-768x470.jpg')

puts "#{Club.count} clubs created!"